version: "3.8"
services:
  app:
    build: .
    ports:
      - "9080:9080"
    environment:
      - NO_SECURE=true
      - DB_URL=Host=host.docker.internal:5432;Database=hue;Username=hue;Password=aa7db17b-f9a0-420f-bec0-4fee3c2d8624;
      - REGISTER_KEY=fd9a7f8f-c492-42d8-a2e9-dad25c7f7395
