CREATE TABLE hue.artist_service (
	service_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	artist_id int4 NULL,
	comm_type_cd int4 null,
	service_nm text null,
	service_desc_tx text null,
	service_base_price_nb int4,
	service_currency_cd varchar(16),
	CONSTRAINT pk_artist_service PRIMARY KEY (service_id),
	CONSTRAINT fk_artist_service_artist FOREIGN KEY (artist_id) REFERENCES hue.artist(artist_id)
);

CREATE TABLE hue.artist_service_addts (
	service_addt_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	service_id int4,
	service_addt_nm text null,
	service_addt_desc_tx text null,
	service_addt_price_nb int4,
	service_addt_limit_nb int4,
	CONSTRAINT pk_artist_service_addt PRIMARY KEY (service_addt_id),
	CONSTRAINT fk_addition_service_id FOREIGN KEY (service_id) REFERENCES hue.artist_service(service_id)
);

