CREATE TABLE hue."user" (
	user_nm VARCHAR(32) NOT NULL,
	pass_tx VARCHAR(64) NOT NULL,
	artist_in BOOL NULL DEFAULT false,
	CONSTRAINT pk_user PRIMARY KEY (user_nm)
);

CREATE TABLE hue.artist (
	artist_id INT4 NOT NULL GENERATED by DEFAULT AS IDENTITY,
	artist_nm VARCHAR(32) NULL,
	artist_social_tx text NULL,
	artist_comm_sheet_tx text NULL,
	user_nm VARCHAR(32) NULL,
	artist_img_bytes BYTEA NULL,
	artist_img_mime_tx VARCHAR NULL,
	CONSTRAINT pk_artist PRIMARY KEY (artist_id),
	CONSTRAINT fk_artist_owner FOREIGN KEY (user_nm) REFERENCES hue."user"(user_nm)
);

CREATE TABLE hue.char_cat (
	char_cat_id INT4 NOT NULL GENERATED by DEFAULT AS IDENTITY,
	char_cat_nm VARCHAR(32) NOT NULL,
	char_cat_desc_tx TEXT NULL,
	char_cat_color_tx VARCHAR(32) NULL,
	user_nm VARCHAR(32) NULL,
	CONSTRAINT pk_char_cat PRIMARY KEY (char_cat_id),
	CONSTRAINT fk_char_cat_owner FOREIGN KEY (user_nm) REFERENCES hue."user"(user_nm)
);

CREATE TABLE hue."char" (
	char_id INT4 NOT NULL GENERATED by DEFAULT AS IDENTITY,
	char_nm VARCHAR(32) NOT NULL,
	char_species_tx TEXT NOT NULL,
	char_desc_tx TEXT NULL,
	char_color_tx VARCHAR(32) NULL,
	user_nm VARCHAR(32) NULL,
	char_img_bytes BYTEA NULL,
	char_img_mime_tx VARCHAR NULL,
	char_cat_id INT4 NULL,
	CONSTRAINT pk_char PRIMARY KEY (char_id),
	CONSTRAINT fk_char_owner FOREIGN KEY (user_nm) REFERENCES hue."user"(user_nm),
	CONSTRAINT fk_char_cat FOREIGN KEY (char_cat_id) REFERENCES hue.char_cat(char_cat_id)
);

CREATE TABLE hue.comm_tag (
	comm_tag_id INT4 NOT NULL GENERATED by DEFAULT AS IDENTITY,
	comm_tag_nm VARCHAR(64) NULL,
	comm_tag_desc_tx TEXT NULL,
	comm_tag_color_tx VARCHAR(32) NULL,
	user_nm VARCHAR(32) NULL,
	CONSTRAINT pk_comm_tag PRIMARY KEY (comm_tag_id),
	CONSTRAINT comm_tag_user_fk FOREIGN KEY (user_nm) REFERENCES hue."user"(user_nm)
);

CREATE TABLE hue.comm (
	comm_id INT4 NOT NULL GENERATED by DEFAULT AS IDENTITY,
	comm_nm VARCHAR(128) NULL,
	comm_desc_tx TEXT NULL,
	comm_price_nb INT4 NULL,
	comm_char_cnt INT4 NULL,
	comm_post_tags_tx TEXT NULL,
	comm_post_desc_tx TEXT NULL,
	comm_status_cd INT4 NULL,
	comm_type_cd INT4 NULL,
	cre_ts TIMESTAMP(6) NOT NULL,
	updt_ts TIMESTAMP(6) NULL,
	start_dt DATE NULL,
	done_dt DATE NULL,
	pblsh_dt DATE NULL,
	artist_id INT4 NULL,
	user_nm VARCHAR(32) NULL,
	comm_header_img_bytes BYTEA NULL,
	comm_header_img_mime_tx VARCHAR NULL,
	CONSTRAINT pk_comm PRIMARY KEY (comm_id),
	CONSTRAINT fk_comm_artist FOREIGN KEY (artist_id) REFERENCES hue.artist(artist_id),
	CONSTRAINT fk_comm_owner FOREIGN KEY (user_nm) REFERENCES hue."user"(user_nm)
);

CREATE TABLE hue.comm_char_map (
	comm_id INT4 NULL,
	char_id INT4 NULL,
	CONSTRAINT fk_comm_char_map_comm FOREIGN KEY (comm_id) REFERENCES hue.comm(comm_id),
	CONSTRAINT fk_comm_char_map_char FOREIGN KEY (char_id) REFERENCES hue."char"(char_id)
);

CREATE TABLE hue.comm_tag_map (
	comm_id INT4 NULL,
	comm_tag_id INT4 NULL,
	CONSTRAINT fk_comm_tag_map_comm FOREIGN KEY (comm_id) REFERENCES hue.comm(comm_id),
	CONSTRAINT fk_comm_tag_map_tag FOREIGN KEY (comm_tag_id) REFERENCES hue.comm_tag(comm_tag_id)
);

ALTER TABLE hue.comm
ADD COLUMN COMM_YEAR_NB INT GENERATED ALWAYS AS (
  EXTRACT(YEAR FROM COALESCE(START_DT, CRE_TS::DATE))
) STORED;

ALTER TABLE hue.comm
ADD COLUMN COMM_STARTED_IN BOOLEAN GENERATED ALWAYS AS (
  COMM_STATUS_CD > 1
) STORED;

ALTER TABLE hue.comm
ADD COLUMN COMM_TTC_NB INT GENERATED ALWAYS AS (
  CASE 
    WHEN DONE_DT IS NOT NULL AND START_DT IS NOT NULL 
    THEN DONE_DT - START_DT
    ELSE NULL
  END
) STORED;

ALTER TABLE hue.comm
ADD COLUMN COMM_MONTH_NB INT GENERATED ALWAYS AS (
  EXTRACT(MONTH FROM COALESCE(START_DT, CRE_TS::DATE))
) STORED;

ALTER TABLE hue.char
	ADD COLUMN PRIMARY_CHAR_IN boolean;


create view hue.AT_A_GLANCE_VIEW as 
SELECT 
    USER_NM,

    -- Total Actual Commissions: Count where COMM_STARTED_IN
    COUNT(CASE WHEN COMM_STARTED_IN THEN 1 END) AS TOTAL_COMM_NB,

    -- Total Spent: Sum(COMM_PRICE_NB) where COMM_STATUS_IN
    SUM(CASE WHEN COMM_STARTED_IN THEN COMM_PRICE_NB ELSE 0 END) AS TOTAL_SPENT_NB,

    -- Total Yet to Commission: Count where NOT COMM_STARTED_IN
    COUNT(CASE WHEN NOT COMM_STARTED_IN THEN 1 END) AS TOTAL_NOT_COMM_NB,

    -- Total Yet to Spend: Sum(COMM_PRICE_NB) where NOT COMM_STATUS_IN
    SUM(CASE WHEN NOT COMM_STARTED_IN THEN COMM_PRICE_NB ELSE 0 END) AS TOTAL_NOT_SPENT_NB,

    -- Average Price (no conditions)
    AVG(COMM_PRICE_NB) AS AVG_PRICE_NB,

    -- Average Time to Completion where time to completion is not null
    AVG(CASE WHEN COMM_TTC_NB IS NOT NULL THEN COMM_TTC_NB END) AS AVG_TTC_NB,

    -- Average Money Spent Per Month: Total Spent / Months with any commissions with COMM_STATUS_IN
    SUM(CASE WHEN COMM_STARTED_IN THEN COMM_PRICE_NB ELSE 0 END) / 
    NULLIF(COUNT(DISTINCT CASE WHEN COMM_STARTED_IN THEN DATE_TRUNC('month', COALESCE(START_DT, CRE_TS::DATE)) END), 0) 
    AS AVG_SPENT_NB,

    -- Average Commissions Per Month: Total Commissions / Months with any commissions regardless of state
    COUNT(*) / 
    NULLIF(COUNT(DISTINCT DATE_TRUNC('month', COALESCE(START_DT, CRE_TS::DATE))), 0) 
    AS AVG_COMM_BY_MONTH_NB
    
FROM 
    hue.comm
GROUP BY 
    USER_NM;

create view hue.YEARLY_AT_A_GLANCE_VIEW as 
SELECT 
    USER_NM,
    COMM_YEAR_NB,

    -- Total Actual Commissions: Count where COMM_STARTED_IN
    COUNT(CASE WHEN COMM_STARTED_IN THEN 1 END) AS TOTAL_COMM_NB,

    -- Total Spent: Sum(COMM_PRICE_NB) where COMM_STATUS_IN
    SUM(CASE WHEN COMM_STARTED_IN THEN COMM_PRICE_NB ELSE 0 END) AS TOTAL_SPENT_NB,

    -- Total Yet to Commission: Count where NOT COMM_STARTED_IN
    COUNT(CASE WHEN NOT COMM_STARTED_IN THEN 1 END) AS TOTAL_NOT_COMM_NB,

    -- Total Yet to Spend: Sum(COMM_PRICE_NB) where NOT COMM_STATUS_IN
    SUM(CASE WHEN NOT COMM_STARTED_IN THEN COMM_PRICE_NB ELSE 0 END) AS TOTAL_NOT_SPENT_NB,

    -- Average Price (no conditions)
    AVG(COMM_PRICE_NB) AS AVG_PRICE_NB,

    -- Average Time to Completion where time to completion is not null
    AVG(CASE WHEN COMM_TTC_NB IS NOT NULL THEN COMM_TTC_NB END) AS AVG_TTC_NB,

    -- Average Money Spent Per Month: Total Spent / Months with any commissions with COMM_STATUS_IN
    SUM(CASE WHEN COMM_STARTED_IN THEN COMM_PRICE_NB ELSE 0 END) / 
    NULLIF(COUNT(DISTINCT CASE WHEN COMM_STARTED_IN THEN DATE_TRUNC('month', COALESCE(START_DT, CRE_TS::DATE)) END), 0) 
    AS AVG_SPENT_NB,

    -- Average Commissions Per Month: Total Commissions / Months with any commissions regardless of state
    COUNT(*) / 
    NULLIF(COUNT(DISTINCT DATE_TRUNC('month', COALESCE(START_DT, CRE_TS::DATE))), 0) 
    AS AVG_COMM_BY_MONTH_NB
    
FROM 
    hue.comm
GROUP BY 
    USER_NM, COMM_YEAR_NB;
   
create view hue.MONTHLY_COMM_PRICE_CAT_VIEW as 
select USER_NM, COMM_YEAR_NB, COMM_MONTH_NB, 
	COUNT(case when COMM_PRICE_NB < 50 then 1 end ) as SMALL_COMM_CNT,
	COUNT(case when COMM_PRICE_NB >= 50 AND COMM_PRICE_NB < 80 then 1 end ) as MED_COMM_CNT,
	COUNT(case when COMM_PRICE_NB >= 80 then 1 end ) as LARGE_COMM_CNT
	from hue.comm group by user_nm, comm_year_nb, comm_month_nb
	order by COMM_YEAR_NB, COMM_MONTH_NB

create view hue.MONTHLY_SPEND_VIEW as 
select USER_NM, COMM_YEAR_NB, COMM_MONTH_NB, 
    SUM(CASE WHEN COMM_STARTED_IN THEN COMM_PRICE_NB ELSE 0 END) AS CONFIRMED_SPENT_NB,
	SUM(CASE WHEN NOT COMM_STARTED_IN THEN COMM_PRICE_NB ELSE 0 END) as POTENTIAL_SPENT_NB
	from hue.comm group by user_nm, comm_year_nb, comm_month_nb
	order by COMM_YEAR_NB, COMM_MONTH_NB;

create view hue.MONTHLY_STATUS_VIEW as 
select USER_NM, COMM_YEAR_NB, COMM_MONTH_NB, 
	COUNT(case when COMM_STATUS_CD = 0 then 1 end ) as BRAINSTORM_CNT,
	COUNT(case when COMM_STATUS_CD = 1 then 1 end ) as SCHEDULED_CNT,
	COUNT(case when COMM_STATUS_CD = 2 then 1 end ) as IN_PROG_CNT,
	COUNT(case when COMM_STATUS_CD = 3 then 1 end ) as DONE_CNT,
	COUNT(case when COMM_STATUS_CD = 4 then 1 end ) as PUBLISH_CNT
	from hue.comm group by user_nm, comm_year_nb, comm_month_nb
	order by COMM_YEAR_NB, COMM_MONTH_NB;

create view hue.YEARLY_CHAR_STATISTICS as 
select co.USER_NM, COMM_YEAR_NB, CH.CHAR_ID, CH.CHAR_NM, CH.CHAR_COLOR_TX, Count(*) as COMM_CNT, sum(COMM_PRICE_NB) as SPENT_NB, max(PBLSH_DT) LAST_PBLSH_DT
from hue.hue.char ch, hue.hue.comm co, hue.hue.comm_char_map cm 
where ch.char_id = cm.char_id  and cm.comm_id = co.comm_id 
group by CO.USER_NM, Ch.CHAR_ID, COMM_YEAR_NB, CH.CHAR_NM, CH.CHAR_COLOR_TX;

create view hue.CHAR_STATISTICS as 
select co.USER_NM, CH.CHAR_ID, CH.CHAR_NM, CH.CHAR_COLOR_TX, Count(*) as COMM_CNT, sum(COMM_PRICE_NB) as SPENT_NB, max(PBLSH_DT) LAST_PBLSH_DT
from hue.hue.char ch, hue.hue.comm co, hue.hue.comm_char_map cm 
where ch.char_id = cm.char_id  and cm.comm_id = co.comm_id 
group by CO.USER_NM, CH.CHAR_ID, CH.CHAR_NM, CH.CHAR_COLOR_TX;

create view hue.YEARLY_ARTIST_STATISTICS as 
select co.USER_NM, COMM_YEAR_NB, co.ARTIST_ID, ar.ARTIST_NM, Count(*) as COMM_CNT, sum(COMM_PRICE_NB) as SPENT_NB, max(PBLSH_DT) LAST_PBLSH_DT
from hue.hue.artist ar, hue.hue.comm co 
where ar.artist_id = co.artist_id 
group by CO.USER_NM, co.artist_id, COMM_YEAR_NB, ar.ARTIST_NM;

create view hue.ARTIST_STATISTICS as 
select co.USER_NM, co.ARTIST_ID, ar.ARTIST_NM, Count(*) as COMM_CNT, sum(COMM_PRICE_NB) as SPENT_NB, max(PBLSH_DT) LAST_PBLSH_DT
from hue.hue.artist ar, hue.hue.comm co 
where ar.artist_id = co.artist_id 
group by CO.USER_NM, co.artist_id, ar.ARTIST_NM;

create view hue.YEARLY_TAG_STATISTICS as 
select co.USER_NM, CO.comm_year_nb, cm.comm_tag_id, ct.COMM_TAG_NM, ct.COMM_TAG_COLOR_TX, Count(*) as COMM_CNT, sum(COMM_PRICE_NB) as SPENT_NB, max(PBLSH_DT) LAST_PBLSH_DT
from hue.hue.comm_tag ct , hue.hue.comm co, hue.hue.comm_tag_map cm 
where ct.comm_tag_id = cm.comm_tag_id  and cm.comm_id = co.comm_id 
group by CO.USER_NM, cm.comm_tag_id , co.comm_year_nb, ct.COMM_TAG_NM, ct.COMM_TAG_COLOR_TX ;

create view hue.TAG_STATISTICS as 
select co.USER_NM, cm.comm_tag_id, ct.COMM_TAG_NM, ct.COMM_TAG_COLOR_TX , Count(*) as COMM_CNT, sum(COMM_PRICE_NB) as SPENT_NB, max(PBLSH_DT) LAST_PBLSH_DT
from hue.hue.comm_tag ct , hue.hue.comm co, hue.hue.comm_tag_map cm 
where ct.comm_tag_id = cm.comm_tag_id  and cm.comm_id = co.comm_id 
group by CO.USER_NM, cm.comm_tag_id, ct.COMM_TAG_NM, ct.COMM_TAG_COLOR_TX  ;