<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Igtampe.BasicLogger" Version="1.1.0" />
    <PackageReference Include="Igtampe.Redistributables" Version="1.0.0" />
    <PackageReference Include="Npgsql" Version="8.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hue.Common\Hue.Common.csproj" />
  </ItemGroup>

</Project>
